### ISSUE TITLE
Unable to build flutter app on ios when using use_frameworks!

### ISSUE THREAD

**Issue by savy-91** [smartlook/smartlook-ios-sdk#10]
Hi, I'm currently experience the following error when trying to build and app with Smartlook (latest version from pub.dev) on an iOS 12.0 iPhone. No problems on Android.

```
/Users/saveriomurgia/development/flutter/.pub-cache/hosted/pub.dartlang.org/sm
    artlook-0.0.4/ios/Classes/SmartlookPlugin.m:2:9: fatal error:
    'Smartlook/Smartlook.h' file not found
    #import <Smartlook/Smartlook.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build
    description

Could not build the precompiled application for the device.
```

**Comment by savy-91** [comment]
After some more debugging, I found out that the problem is that I have this line:
`use_frameworks!`
in my Podfile. Unfortunately I cannot remove it as it is required by another package I am using, do you have any suggestion on how to work around this?

**Comment by pavel-kroh-smartlook** [comment]
Hi, coincidently we were working on a new version at the time that should fix this issue. It was released last Friday (October 4th). Please update to the latest version and let us know whether the issue is solved.

**Comment by savy-91** [comment]
@pavel-kroh-smartlook I checked and I can confirm you that the issue is solved with the latest version you released :) Thanks!

**Comment by pavel-kroh-smartlook** [comment]
Thanks for the feedback! Hopefully we have some durable solution now.
