### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by savy-91** [smartlook/smartlook-ios-sdk#11]
Hi! We are using smartlook v0.0.5 for flutter and it came to my attention that the warning we are receiving from Apple during our Testflight testing phase:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Comes from Smartlook. Is there any chance you plan to upgrade the library to avoid using the deprecated API?

Thanks!

**Comment by alexpluto** [comment]
We would also love this to be fixed! Firebase had a similar issue with some libraries and this is now resolved for them.

**Comment by pavel-kroh-smartlook** [comment]
In short, it will be removed in the next version of iOS Smartlook SDK.

Some background: we only recently started calling a deprecate UIWebView API in order to support hiding sensitive data in embedded web views. However, in the light of this warning, we decided to drop supporting this functionality in the deprecated UIWebView and keep it on WKWebView only so we can remove the API calls that most likely cause this warning. We do not need UIWebView for anything in our SDK itself.

**Comment by pavel-kroh-smartlook** [comment]
The `UIWebView` API is no longer called in the SDK.

https://github.com/smartlook/smartlook-ios-sdk#126---2019-12-02

**Comment by savy-91** [comment]
HI @pavel-kroh-smartlook do you know when the Flutter SDK will be updated with the new iOS SDK version?

I downloaded the archive of the latest Flutter version (0.0.7) and if i'm not mistaken it looks like it's using 1.2.0.

```
//
//  Smartlook.h
//  Smartlook iOS SDK 1.2.0
//
//  Copyright © 2019 Smartsupp.com, s.r.o. All rights reserved.
//
```

**Comment by pavel-kroh-smartlook** [comment]
Trying my best to upgrade the package, however, got stuck with Flutter "blank screen issue"  https://github.com/flutter/flutter/issues/36247 and cannot really test or do anything... as the upgrade is no longer a simple replacing of the binary, cannot really predict when the plugin will be updated.

**Comment by pavel-kroh-smartlook** [comment]
FYI: Apple deadlines are set now, hopefully Flutter fixes the issue so we can catch them:  https://developer.apple.com/news/?id=12232019b

**Comment by savy-91** [comment]
> Trying my best to upgrade the package, however, got stuck with Flutter "blank screen issue" [flutter/flutter#36247](https://github.com/flutter/flutter/issues/36247) and cannot really test or do anything... as the upgrade is no longer a simple replacing of the binary, cannot really predict when the plugin will be updated.

Hi Pavel, did you manage to try again with the latest flutter stable/beta releases by any chance?

**Comment by pavel-kroh-smartlook** [comment]
Hi @savy-91 , we ( @adamblack ) are working on Flutter release now, and it seems working again fo us. The release should be out in few days.
