### ISSUE TITLE
Crashed: com.Smarlook.Smartlook.CacheManagerQueue

### ISSUE THREAD

**Issue by mj-iosdev** [smartlook/smartlook-ios-sdk#13]
**Smartlook Version**:  0.1.12

**OS** : 10.1.0

**Model** : iPhone 5c

Crash Log : 

Crashed: com.Smarlook.Smartlook.CacheManagerQueue
0  libobjc.A.dylib                0x1bc645c4 objc_retain + 3
1  JewelStudio                    0xfb573d -[SLModelKeyboardEvent encodeWithCoder:] + 7085414
2  Foundation                     0x1d27f0b1 _encodeObject + 1048
3  Foundation                     0x1d28029d -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 412
4  Foundation                     0x1d27f0b1 _encodeObject + 1048
5  JewelStudio                    0xfd3e8b -[SLRecordingSegment encodeWithCoder:] + 7210164
6  Foundation                     0x1d27f0b1 _encodeObject + 1048
7  Foundation                     0x1d28029d -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 412
8  Foundation                     0x1d27f0b1 _encodeObject + 1048
9  JewelStudio                    0xfcb6a3 -[SLSession encodeWithCoder:] + 7175372
10 Foundation                     0x1d27f0b1 _encodeObject + 1048
11 Foundation                     0x1d2df27d +[NSKeyedArchiver archiveRootObject:toFile:] + 190
12 JewelStudio                    0xfb0edb __30-[SLCacheManager saveSession:]_block_invoke + 7066884
13 libdispatch.dylib              0x1c091097 _dispatch_call_block_and_release + 10
14 libdispatch.dylib              0x1c09dec5 _dispatch_queue_serial_drain + 840
15 libdispatch.dylib              0x1c094379 _dispatch_queue_invoke + 566
16 libdispatch.dylib              0x1c09fa91 _dispatch_root_queue_drain + 378
17 libdispatch.dylib              0x1c09f8b7 _dispatch_worker_thread3 + 106
18 libsystem_pthread.dylib        0x1c246937 _pthread_wqthread + 1168
19 libsystem_pthread.dylib        0x1c24648c start_wqthread + 8

**Comment by pavel-kroh-smartlook** [comment]
Hi, Smartlook 0.1.12 is very outdated and no longer supported. Where did you get it from? Please upgrade to the latest Smartlook version (1.2.7) and let us know if you still experience the same error.

**Comment by pavel-kroh-smartlook** [comment]
As there is reaction, closing the issue.
