### ISSUE TITLE
Crash on [SLModelKeyboardEvent eventRecordingDictionary]

### ISSUE THREAD

**Issue by mj-iosdev** [smartlook/smartlook-ios-sdk#14]
**Smartlook Version**: 0.1.12

**OS**: 10.3.4

**Model**: iPhone 5

**Crash Log** :

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1a1c4dd6 objc_msgSend + 21
1  JewelStudio                    0x10223df -[SLModelKeyboardEvent eventRecordingDictionary] + 7084552
2  JewelStudio                    0x1042cff -[SLRecordingSegment eventsDictionariesWithEventClass:] + 7217960
3  JewelStudio                    0x1044461 -[SLRecordingSegment eventDataDictionary] + 7223946
4  JewelStudio                    0x102c239 -[SLApiManager sendSessionRecordingSegment:completionBlock:] + 7125090
5  JewelStudio                    0x103ff09 -[SLRecordingSegment uploadSegmentWithCompletionBlock:] + 7206194
6  JewelStudio                    0x10455ad __53-[SLRecordingSegment sendOfflineWithCompletionBlock:]_block_invoke_2 + 7228374
7  JewelStudio                    0x102dd33 __73-[SLApiManager sendAnalyticsEvents:withRecordingSegment:completionBlock:]_block_invoke + 7131996
8  JewelStudio                    0x102e875 __64-[SLApiManager postPath:queryParams:jsonObject:completionBlock:]_block_invoke_2 + 7134878
9  libdispatch.dylib              0x1a5fd797 _dispatch_call_block_and_release + 10
10 libdispatch.dylib              0x1a5fd783 _dispatch_client_callout + 22
11 libdispatch.dylib              0x1a601d05 _dispatch_main_queue_callback_4CF + 902
12 CoreFoundation                 0x1aeebd69 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
13 CoreFoundation                 0x1aee9e19 __CFRunLoopRun + 848
14 CoreFoundation                 0x1ae3d1af CFRunLoopRunSpecific + 470
15 CoreFoundation                 0x1ae3cfd1 CFRunLoopRunInMode + 104
16 GraphicsServices               0x1c5e7b41 GSEventRunModal + 80
17 UIKit                          0x201c5a53 UIApplicationMain + 150
18 JewelStudio                    0xdd883 main + 32 (AppDelegate.swift:32)
19 libdyld.dylib                  0x1a62a4eb <redacted> + 2

**Comment by pavel-kroh-smartlook** [comment]
Hi, Smartlook 0.1.12 is very outdated and no longer supported. Where did you get it from? Please upgrade to the latest Smartlook version (1.2.7) and let us know if you still experience the same error.

**Comment by pavel-kroh-smartlook** [comment]
As there is reaction, closing the issue.
