### ISSUE TITLE
Crash inside Smartlook framwework with RichEdiorView usage

### ISSUE THREAD

**Issue by sridivyaTechjini** [smartlook/smartlook-ios-sdk#15]
Cannot remove an observer <SLChangesDetector 0x28359d400> for the key path "contentOffset" from <WKContentViewMinusAccessoryView 0x1170c5000> because it is not registered as an observer.

**Comment by pavel-kroh-smartlook** [comment]
We found the probable cause ( https://github.com/cjwirth/RichEditorView/blob/2aa67881e596639effa095aab4a93a73ba98b512/RichEditorView/Classes/CJWWebView%2BHackishAccessoryHiding.m#L68 ), but are unable to reproduce the error. Working on a workaround solution, that will be part of the next release.

**Comment by pavel-kroh-smartlook** [comment]
An error in a third party component we cannot reproduce. Won't fix.
