### ISSUE TITLE
UIWebView Deprecated - Still in Smartlook framework

### ISSUE THREAD

**Issue by nateboxer** [smartlook/smartlook-ios-sdk#16]
I see this issue was marked resolved, but I still get warnings about it from the app store. I'm using Smartlook framework 1.2.7. I've cleaned the project, deleted dynamic libraries, etc. The app store sends me a deprecation warning every time I submit my app.

**Comment by pavel-kroh-smartlook** [comment]
The UIWebView was removed in 1.2.7, we double-checked it. Does upgrade to the recent version helps?

**Comment by nateboxer** [comment]
I still get the warning from the app store. I'm using version 1.3.0 of Smartlook framework.

**Comment by pavel-kroh-smartlook** [comment]
When we removed UIWebView from the code in 1.2.7, we tested an AppStore upload and got no warning. I double-checked the code and there is no trace of UIWebView in there. We can check the upload later again, but I do not think there is this kind of regression in our code.

**Comment by nateboxer** [comment]
This has finally gone away. Thank you
