### ISSUE TITLE
Smartlook slows down app launch by ~11 seconds, and then slows 

### ISSUE THREAD

**Issue by Ryanauger95** [smartlook/smartlook-ios-sdk#19]
I have read on some of your earlier issues that you are aware of this warning. Is there any way to prevent the crazy increase in launch time though?

```
Main Thread Checker: UI API called on a background thread: -[UIView drawViewHierarchyInRect:afterScreenUpdates:]
PID: 1199, TID: 172442, Thread name: (none), Queue name: com.Smarlook.Smartlook.SnapshotQueue, QoS: 17
Backtrace:
```

We call `Smartlook.startRecording()` in didFinishLaunchingWithOptions, and then after this error, our launch screen hangs for an additional 11-12 seconds (consistently). Is there anything we can do to alleviate this?

**Comment by pavel-kroh-smartlook** [comment]
It is described in the documentation: https://smartlook.github.io/docs/sdk/ios/#a-technical-note-main-thread-checker-warning
