### ISSUE TITLE
RNSmartlook not mapped in NativeModules

### ISSUE THREAD

**Issue by supolik** [smartlook/smartlook-ios-sdk#4]
SDK installed as instructed in https://smartlook.github.io/docs/sdk/react-native/

For IOS i found that RNSmartlook is not mapped in NativeModules in file Smartlook-react-native-wrapper/interceptor.js

```
var SmartlookBridge = NativeModules.RNSmartlook;
```

**Comment by adamblack** [comment]
Hi @supolik  ,

thank you for using Smartlook!

Could you please also try invocation as described in docs:

var Smartlook = require('smartlook-react-native-wrapper');
Smartlook.init("KEY");

?

**Comment by supolik** [comment]
I use the equivalent of ES6

```
import Smartlook from 'smartlook-react-native-wrapper';
Smartlook.init("KEY");
```
Now I'm trying use Appsee in same way and it works right (https://www.appsee.com/docs/ios/reactnative)

**Comment by Titozzz** [comment]
Hello @adamblack , same issue here.

**Comment by pavel-kroh-smartlook** [comment]
Hi all, few days ago we released new version of React Native package that uses different approach to embedding the SDK and it should solve this issue.
