### ISSUE TITLE
Scroll freezes in UITableView 

### ISSUE THREAD

**Issue by itishenko** [smartlook/smartlook-ios-sdk#5]
Thank you a lot for a good product, we are happy to use this with our apps! However, sadly we've recently found an annoying issue that appeared after initing of SDK. 

That can be easily reproduced if you present any controller contained UITableView inside UINavigationController. Then if you double tap on a left edge of any cell (on digits in the demo), you will get a freeze of the scroll for the table! This is curiously but it could be resolved only with disabling initializing of SDK.

There is a sample app with a demo of this issue in my GitHub:
https://github.com/itishenko/SmartlookTest

**Comment by pavel-kroh-smartlook** [comment]
Hi @itishenko , thanks for your report and effort with the demo, very helpful! 

We are looking into the issue, pinpointed what causes it and now we are working on a solution or workaround as the cause of it (non-standard behaviour of a system class in this isolated case) has probably no straightforward solution.

**Comment by pavel-kroh-smartlook** [comment]
Thanks again for the report. The issue was solved during heavy refactoring of the SDK in one of the latest versions.
