### ISSUE TITLE
App Crashes immediately when launches 

### ISSUE THREAD

**Issue by YutaLin** [smartlook/smartlook-ios-sdk#7]
I install smartlook via cocoapods and install successfully, but when I launches app, it crashes immediately.

**Comment by Acro** [comment]
@YutaLin Hello, can you give us more information (such as stack trace, etc)?

**Comment by pavel-kroh-smartlook** [comment]
As there is no further info and several new versions of SDK were successfully launched in the meantime, let me close this issue.
