### ISSUE TITLE
No such file or directory warnings in Xcode 10

### ISSUE THREAD

**Issue by kristiyandobrev** [smartlook/smartlook-ios-sdk#8]
Since we have updated our app to `1.1.0` we are getting bunch of warnings in Xcode. Updating to `1.2.0` made no difference. 

<img width="1792" alt="Screenshot 2019-09-13 at 16 41 17" src="https://user-images.githubusercontent.com/8437817/64871510-aae91400-d645-11e9-87c2-6a128a280d61.png">

We tried to add a post installer in the `Podfile` to get rid of the debug information but unfortunately that didn't work at all. 

```
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'Smartlook'
                target.build_configurations.each do |config|
                    config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
                end
            end
        end
    end

```

**Comment by pavel-kroh-smartlook** [comment]
Hi we are aware about this issue. The warnings are harmful yet annoying. Our observation is that this appears when in the Xcode project, in target build options, debug information format is set to `DWARF with dSYM File`  for DEBUG profile. This is not the default setting, and is typically set  when the app uses Fabric's Crashlytic or such. We tried to get rid of it by deploying varions compilation and build flags with no avail so far.
