### ISSUE TITLE
SmartLook crashes on app launch

### ISSUE THREAD

**Issue by garush13** [smartlook/smartlook-ios-sdk#9]
You can see the stack trace above.
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x22cd25ab8 (Missing)
1  libobjc.A.dylib                0x22bf2ad00 (Missing)
2  AVFoundation                   0x232de7220 (Missing)
3  AVFoundation                   0x232de6b88 (Missing)
4  LiveBoard                      0x104adcf60 __78-[SLRecordingSegment initWithSessionSettings:offsetTime:startTimestamp:index:]_block_invoke + 236 (SLRecordingSegment.m:236)
5  libdispatch.dylib              0x22c733308 (Missing)
6  libdispatch.dylib              0x22c734888 (Missing)
7  libdispatch.dylib              0x22c73bdd4 (Missing)
8  libdispatch.dylib              0x22c73c918 (Missing)
9  libdispatch.dylib              0x22c744cc0 (Missing)
10 libsystem_pthread.dylib        0x22c930a98 (Missing)
11 libsystem_pthread.dylib        0x22c936dc4 (Missing)

**Comment by pavel-kroh-smartlook** [comment]
This bug is solved in the latest version of Smartlook 1.2.1.
